import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String, Uuid, func, CheckConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.tool import Tool


class ToolUsage(Base):
    """
    Tracks individual tool usage events for analytics and usage-based features.
    
    Sessions are anonymous and identified by session_id. Token counts enable
    cost tracking for premium AI providers.
    """
    __tablename__ = "tool_usage"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    tool_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("tools.id", ondelete="RESTRICT"),
        nullable=False, index=True,
        doc="Reference to the tool used"
    )
    session_id: Mapped[str] = mapped_column(
        String(255), nullable=False, index=True,
        doc="Unique session identifier for anonymous user tracking"
    )
    ip_hash: Mapped[str | None] = mapped_column(
        String(255), nullable=True,
        doc="Hashed IP address for abuse detection (privacy-preserving)"
    )
    language: Mapped[str | None] = mapped_column(
        String(50), nullable=True,
        doc="Language code used in the request (en, ne, etc.)"
    )
    input_tokens: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0",
        doc="Tokens consumed by input to AI provider"
    )
    output_tokens: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0",
        doc="Tokens generated by AI provider"
    )
    status: Mapped[str] = mapped_column(
        String(50), nullable=False,
        doc="Result status (success, error, rate_limited, etc.)"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(),
        doc="When this usage event occurred"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(),
        onupdate=func.now(),
        doc="Last time this record was updated"
    )

    # Relationships
    tool: Mapped["Tool"] = relationship(
        "Tool",
        foreign_keys=[tool_id],
        doc="Reference to the tool used"
    )

    __table_args__ = (
        # Composite index for common query patterns: filtering by session and date
        Index("ix_tool_usage_session_created", "session_id", "created_at", postgresql_where=None),
        # Index for aggregation queries: count by tool over time
        Index("ix_tool_usage_tool_created", "tool_id", "created_at"),
        # Index for abuse detection: check session activity patterns
        Index("ix_tool_usage_session_status", "session_id", "status"),
        CheckConstraint("input_tokens >= 0", name="ck_tool_usage_input_tokens_non_negative"),
        CheckConstraint("output_tokens >= 0", name="ck_tool_usage_output_tokens_non_negative"),
        CheckConstraint("length(status) > 0", name="ck_tool_usage_status_not_empty"),
    )
